---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Launch EC2 instance on Amazon"
      ec2: >
          keypair={{mykeypair}}
          group={{security_group}}
          instance_type={{instance_type}}
          image={{image}}
          region={{region}}
          wait=true
          ec2_access_key={{ec2_access_key}}
          ec2_secret_key={{ec2_secret_key}}

      register: ec2

    - name: "Add new instance to host group"
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: "Wait for the instance"
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: "Deploy the whole site inside instance"
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    - ../nginx
#   - waitress
