---
- hosts: localhost
  connection: local
  user: ubuntu
  sudo: True
  gather_facts: False

  tasks:
  - name: "Launch basic cloudformation"
    action: cloudformation stack_name="biostar-central" state=present region=eu-west-1 disable_rollback=yes template=templates/aws_cloudformation.cf
    args:
      template_parameters:
        KeyName: "{{ mykeypair }}"
        InstanceType: "{{ instance_type }}"
      tags:
        Stack: biostar-central
    register: stack

  - name: "Show instance attributes"
    debug: msg="The instance attributes are {{stack.stack_outputs}}"

  - name: "Add new instance to host group"
    local_action: add_host hostname={{ stack.stack_outputs.PublicIP }} groupname=launched

- name: "Deploy the whole site inside instance"
  hosts: launched
  user: ubuntu
  sudo: True
  gather_facts: True
  roles:
    - ../nginx
