---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: "Launch basic cloudformation"
    action: cloudformation stack_name="biostar-central" state=present region=eu-west-1 disable_rollback=yes template=templates/aws_cloudformation.cf
    args:
      template_parameters:
        KeyName: "{{ mykeypair }}"
        InstanceType: "{{ instance_type }}"
      tags:
        Stack: biostar-central

    register: ec2

  - name: "Add new instance to host group"
    local_action: add_host hostname={{ item.public_ip }} groupname=launched
    with_items: ec2.instances

  - name: "Wait for the instance"
    local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances

- name: "Deploy the whole site inside instance"
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    - ../nginx
