---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Provision the whole site on Amazon"
      ec2: >
          keypair={{mykeypair}}
          group={{security_group}}
          instance_type={{instance_type}}
          image={{image}}
          wait=true
          ec2_access_key={{ec2_access_key}}
          ec2_secret_key={{ec2_secret_key}}
          
      register: biostars
