- name: "Create GCE instance"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
      libcloud_ca: ca-bundle.crt

  tasks:
   - name: "Download CA keychain for apache-libcloud"
     command: wget https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
     environment: 
        SSL_CERT_FILE: libcloud_ca

   - name: "Launch instances"
     gce:
         instance_names: biostar
         machine_type: n1-standard-1
         image: debian-7
         service_account_email: "{{ gce_dev_id }}"
         pem_file: "{{ gce_pem_path }}"
         project_id: "{{ gce_prj_id }}"
