---
- name: Ensure PostgreSQL is listening on all localhost
  lineinfile: dest=/etc/postgresql/9.1/main/postgresql.conf
    regexp='^#?listen_addresses\s*='
    line="listen_addresses = '127.0.0.1'"
    state=present
  notify: restart postgresql

- lineinfile: dest=/etc/postgresql/9.1/main/pg_hba.conf
             regexp='host\s+all\s+all\s+127.0.0.1/32\s+trust'
             line='host all all 127.0.0.1/32 md5'
             insertbefore=BOF
  notify: restart postgresql

